# GCP projecregion
project_id: bank-loan-analytics        
region: asia-south1                        

# Google Cloud Storage settings
gcs:
  bucket: asia-south1-bank-loan-pipel-2d7d7a70-bucket            
  raw_prefix: data/                   

# BigQuery settings
bigquery:
  dataset: credit_risk                       
  staging_table: loan_applications_stg            
  curated_table: loan_applications_curated             

# Airflow / Composer
composer:
  dag_name: bank_loan_pipeline

# Paths inside this repo (helps scripts & DAGs find assets)
paths:
  transform_sql: sql/01_staging.sql   
